apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  template:
    spec:
      containers:
        - name: default
          image: grammerly
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 1Gi