apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
        - name: default
          command: ["yarn"]
          args: ["build-and-start"]
          ports:
            - containerPort: 8000

